// <auto-generated />
using System;
using Construlink.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Construlink.Migrations
{
    [DbContext(typeof(BaseControleContext))]
    [Migration("20250710151536_InitBaseControle")]
    partial class InitBaseControle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Construlink.Models.Avisos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime")
                        .HasColumnName("DataFim");

                    b.Property<TimeSpan?>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("Mensagem");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("Construlink.Models.CrmAuditorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comportamento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMPORTAMENTO");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA");

                    b.Property<int?>("Utilizadorid")
                        .HasColumnType("int")
                        .HasColumnName("UTILIZADORID");

                    b.HasKey("Id");

                    b.ToTable("CRM_AUDITORIA");
                });

            modelBuilder.Entity("Construlink.Models.CrmConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Option")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("OPTION");

                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("CRM_CONFIG");
                });

            modelBuilder.Entity("Construlink.Models.CrmEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseNome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cor1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cor2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cor3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Favicon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagemCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagemIndex")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoNavBar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumeroPicagens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CRM_EMPRESAS");
                });

            modelBuilder.Entity("Construlink.Models.CrmSerieDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Erpid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ERPID");

                    b.Property<bool?>("Isdefault")
                        .HasColumnType("bit")
                        .HasColumnName("ISDEFAULT");

                    b.Property<string>("Layoutid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LAYOUTID");

                    b.Property<int?>("Lojaid")
                        .HasColumnType("int")
                        .HasColumnName("LOJAID");

                    b.Property<string>("Serie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SERIE");

                    b.Property<string>("Setorerp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SETORERP");

                    b.Property<int?>("Tipodocumentoid")
                        .HasColumnType("int")
                        .HasColumnName("TIPODOCUMENTOID");

                    b.Property<int?>("Ultimodocumento")
                        .HasColumnType("int")
                        .HasColumnName("ULTIMODOCUMENTO");

                    b.HasKey("Id");

                    b.ToTable("CRM_SERIE_DOCUMENTO");
                });

            modelBuilder.Entity("Construlink.Models.CrmUtilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agpassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AGPASSWORD");

                    b.Property<bool?>("BancoHoras")
                        .HasColumnType("bit")
                        .HasColumnName("BANCO_HORAS");

                    b.Property<DateTime?>("BancoHorasData")
                        .HasColumnType("datetime")
                        .HasColumnName("BANCO_HORAS_DATA");

                    b.Property<decimal?>("BancoHorasStart")
                        .HasColumnType("decimal(10, 1)")
                        .HasColumnName("BANCO_HORAS_START");

                    b.Property<decimal?>("BancoHorasTurno")
                        .HasColumnType("decimal(10, 1)")
                        .HasColumnName("BANCO_HORAS_TURNO");

                    b.Property<bool?>("Changepassword")
                        .HasColumnType("bit")
                        .HasColumnName("CHANGEPASSWORD");

                    b.Property<string>("Departamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DEPARTAMENTO");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Empresa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMPRESA");

                    b.Property<bool?>("FazPicagens")
                        .HasColumnType("bit")
                        .HasColumnName("FAZ_PICAGENS");

                    b.Property<string>("Funconario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FUNCONARIO");

                    b.Property<bool?>("Geolocation")
                        .HasColumnType("bit")
                        .HasColumnName("GEOLOCATION");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InicioTimesheets")
                        .HasColumnType("datetime")
                        .HasColumnName("INICIO_TIMESHEETS");

                    b.Property<bool?>("IsApenasPicagens")
                        .HasColumnType("bit")
                        .HasColumnName("IsApenasPicagens");

                    b.Property<bool?>("IsCliente")
                        .HasColumnType("bit")
                        .HasColumnName("IsCliente");

                    b.Property<bool?>("IsConstrutor")
                        .HasColumnType("bit")
                        .HasColumnName("IsConstrutor");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool?>("IsFuncionario")
                        .HasColumnType("bit")
                        .HasColumnName("IsFuncionario");

                    b.Property<bool?>("IsGestorObra")
                        .HasColumnType("bit")
                        .HasColumnName("IsGestorObra");

                    b.Property<bool?>("IsPromotor")
                        .HasColumnType("bit")
                        .HasColumnName("IsPromotor");

                    b.Property<bool?>("IsSuperAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IS_SUPER_ADMIN");

                    b.Property<bool?>("IsVendedor")
                        .HasColumnType("bit")
                        .HasColumnName("IsVendedor");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool?>("Isadmin")
                        .HasColumnType("bit")
                        .HasColumnName("ISADMIN");

                    b.Property<bool?>("Ismanager")
                        .HasColumnType("bit")
                        .HasColumnName("ISMANAGER");

                    b.Property<DateTime?>("Lastlogon")
                        .HasColumnType("datetime")
                        .HasColumnName("LASTLOGON");

                    b.Property<string>("Macaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MACADDRESS");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("NomeTurno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Pin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PIN");

                    b.Property<string>("Pin2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PIN2");

                    b.Property<bool?>("PreencheTs")
                        .HasColumnType("bit")
                        .HasColumnName("PREENCHE_TS");

                    b.Property<int?>("Reportto")
                        .HasColumnType("int")
                        .HasColumnName("REPORTTO");

                    b.Property<string>("UserCf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_CF");

                    b.Property<string>("Username")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USERNAME");

                    b.Property<bool?>("ValidaPicagens")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDA_PICAGENS");

                    b.HasKey("Id");

                    b.ToTable("CRM_UTILIZADOR");
                });

            modelBuilder.Entity("Construlink.Models.CrmUtilizadorFacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biomarkers")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BIOMARKERS");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int")
                        .HasColumnName("ID_UTILIZADOR");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("CRM_UTILIZADOR_FACIAL");
                });

            modelBuilder.Entity("Construlink.Models.EstadoManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EstadoManutencao");
                });

            modelBuilder.Entity("Construlink.Models.Manutencoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("HoraRetorno")
                        .HasColumnType("time");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("Mensagem");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("Construlink.Models.PatchNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("Data");

                    b.Property<bool?>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTitulo")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("Mensagem");

                    b.HasKey("Id");

                    b.ToTable("PatchNotes");
                });

            modelBuilder.Entity("Construlink.Models.UtilizadorEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UtilizadorEmpresa");
                });

            modelBuilder.Entity("Construlink.Models.UtilizadorEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UtilizadorEntidade");
                });
#pragma warning restore 612, 618
        }
    }
}
