// <auto-generated />
using System;
using Construlink.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Construlink.Migrations.Construlink
{
    [DbContext(typeof(ConstrulinkContext))]
    [Migration("20250710151813_InitConstrulink")]
    partial class InitConstrulink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodigoPostal", b =>
                {
                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente");

                    b.Property<int?>("CodArteria")
                        .HasColumnType("int")
                        .HasColumnName("cod_arteria");

                    b.Property<byte>("CodConcelho")
                        .HasColumnType("tinyint")
                        .HasColumnName("cod_concelho");

                    b.Property<byte>("CodDistrito")
                        .HasColumnType("tinyint")
                        .HasColumnName("cod_distrito");

                    b.Property<string>("CodLocalidade")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("cod_localidade");

                    b.Property<string>("DesigPostal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("desig_postal");

                    b.Property<short>("ExtCodPostal")
                        .HasColumnType("smallint")
                        .HasColumnName("ext_cod_postal");

                    b.Property<string>("LocalArteria")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("local_arteria");

                    b.Property<string>("NomeArteria")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nome_arteria");

                    b.Property<string>("NomeLocalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_localidade");

                    b.Property<short>("NumCodPostal")
                        .HasColumnType("smallint")
                        .HasColumnName("num_cod_postal");

                    b.Property<string>("Porta")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("porta");

                    b.Property<string>("Prep1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("prep1");

                    b.Property<string>("Prep2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("prep2");

                    b.Property<string>("TipoArteria")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tipo_arteria");

                    b.Property<string>("TituloArteria")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("titulo_arteria");

                    b.Property<string>("Troco")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("troco");

                    b.ToTable("codigos_postais");
                });

            modelBuilder.Entity("Concelho", b =>
                {
                    b.Property<byte>("CodConcelho")
                        .HasColumnType("tinyint")
                        .HasColumnName("cod_concelho");

                    b.Property<byte>("CodDistrito")
                        .HasColumnType("tinyint")
                        .HasColumnName("cod_distrito");

                    b.Property<string>("NomeConcelho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_concelho");

                    b.ToTable("concelhos");
                });

            modelBuilder.Entity("Construlink.Models.ColaboradorEPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtribuicao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdColaborador")
                        .HasColumnType("int");

                    b.Property<int?>("IdEpi")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeEpi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ColaboradorEPIs");
                });

            modelBuilder.Entity("Construlink.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("ContratoAtivo")
                        .HasColumnType("bit")
                        .HasColumnName("ContratoAtivo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("DataInicio");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("HoraExtraSubsequent")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("HoraExtraSub");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario");

                    b.Property<string>("Nome")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NumMecanografico")
                        .HasColumnType("int")
                        .HasColumnName("NumMecanografico");

                    b.Property<decimal?>("OrdenadoBase")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("OrdenadoBase");

                    b.Property<decimal?>("OrdenadoHora")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("OrdenadoHora");

                    b.Property<bool?>("PeriodoExperiencia")
                        .HasColumnType("bit")
                        .HasColumnName("PeriodoExperiencia");

                    b.Property<bool?>("Pica4")
                        .HasColumnType("bit")
                        .HasColumnName("Pica4");

                    b.Property<decimal?>("PrimeiraHoraExtra")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PrimeiraHoraExtra");

                    b.Property<string>("TipoContrato")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Construlink.Models.CrmAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("categoria");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_path");

                    b.HasKey("Id");

                    b.ToTable("CRM_ANEXOS");
                });

            modelBuilder.Entity("Construlink.Models.CrmAusencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CriadaPor")
                        .HasColumnType("int")
                        .HasColumnName("CriadaPor");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DataCriacao");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime")
                        .HasColumnName("DataEdicao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("DataInicio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EditadaPor")
                        .HasColumnType("int")
                        .HasColumnName("EditadaPor");

                    b.Property<TimeSpan?>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("HoraFim");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("HoraInicio");

                    b.Property<int>("IdColaborador")
                        .HasColumnType("int")
                        .HasColumnName("IdColaborador");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("NomeColaborador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Observacoes");

                    b.Property<string>("TipoAusencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdColaborador");

                    b.ToTable("CrmAusencias");
                });

            modelBuilder.Entity("Construlink.Models.CrmConcelho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Custo")
                        .HasColumnType("decimal(37, 8)")
                        .HasColumnName("CUSTO");

                    b.Property<decimal?>("Custo2")
                        .HasColumnType("decimal(37, 8)")
                        .HasColumnName("CUSTO2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Distritoid")
                        .HasColumnType("int")
                        .HasColumnName("DISTRITOID");

                    b.HasKey("Id");

                    b.ToTable("CRM_CONCELHO");
                });

            modelBuilder.Entity("Construlink.Models.CrmConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Option")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("OPTION");

                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("CRM_CONFIG");
                });

            modelBuilder.Entity("Construlink.Models.CrmDistrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Paisid")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("PAISID");

                    b.HasKey("Id");

                    b.ToTable("CRM_DISTRITO");
                });

            modelBuilder.Entity("Construlink.Models.CrmEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseNome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cor1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cor2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cor3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Favicon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagemCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagemIndex")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoNavBar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumeroPicagens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CRM_EMPRESAS");
                });

            modelBuilder.Entity("Construlink.Models.CrmEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CcValidade")
                        .HasColumnType("datetime2")
                        .HasColumnName("ccValidade");

                    b.Property<string>("Ccentidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ccEntidade");

                    b.Property<string>("Codigo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("codigo_postal");

                    b.Property<int?>("Concelho")
                        .HasColumnType("int")
                        .HasColumnName("concelho");

                    b.Property<int?>("CondPagamento")
                        .HasColumnType("int")
                        .HasColumnName("cond_Pagamento");

                    b.Property<string>("CpLoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CpLoc");

                    b.Property<DateTime?>("DataUpd")
                        .HasColumnType("datetime")
                        .HasColumnName("data_upd");

                    b.Property<int?>("Distrito")
                        .HasColumnType("int")
                        .HasColumnName("distrito");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("fax");

                    b.Property<string>("Iban")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("iban");

                    b.Property<string>("IdPrimavera")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("IdPrimavera");

                    b.Property<bool?>("IsPotencial")
                        .HasColumnType("bit")
                        .HasColumnName("IsPotencial");

                    b.Property<bool>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<bool?>("Isentoiva")
                        .HasColumnType("bit")
                        .HasColumnName("isentoiva");

                    b.Property<string>("Localidade")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("localidade");

                    b.Property<string>("Moeda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Moeda");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("morada");

                    b.Property<string>("Morada2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("morada2");

                    b.Property<int?>("Motivoisencao")
                        .HasColumnType("int")
                        .HasColumnName("motivoisencao");

                    b.Property<string>("Nib")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nib");

                    b.Property<string>("Nif")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nif");

                    b.Property<int?>("NivelPreco")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFiscal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("nome_fiscal");

                    b.Property<string>("NomeNivelPreco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomeNivelPreco");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pais");

                    b.Property<decimal?>("Plafond")
                        .HasColumnType("numeric(18, 3)")
                        .HasColumnName("plafond");

                    b.Property<string>("Site")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("site");

                    b.Property<string>("Situacao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("situacao");

                    b.Property<string>("Swift")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("swift");

                    b.Property<string>("Telefone")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("telefone");

                    b.Property<string>("Telemovel")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("telemovel");

                    b.Property<string>("TipoEntidade")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("tipo_entidade");

                    b.Property<string>("TipoMercado")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("TipoMercado");

                    b.Property<string>("TipoPreco")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("tipo_preco");

                    b.Property<string>("Vendedor")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("vendedor");

                    b.Property<string>("Zona")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.ToTable("CRM_ENTIDADE");
                });

            modelBuilder.Entity("Construlink.Models.CrmEntidadeMetum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EntidadeId")
                        .HasColumnType("int")
                        .HasColumnName("entidade_id");

                    b.Property<string>("MetaKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("meta_key");

                    b.Property<string>("MetaValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meta_value");

                    b.HasKey("Id");

                    b.ToTable("CRM_ENTIDADE_META");
                });

            modelBuilder.Entity("Construlink.Models.CrmFalta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Falta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CRM_FALTAS");
                });

            modelBuilder.Entity("Construlink.Models.CrmFeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DATA");

                    b.HasKey("Id");

                    b.ToTable("CRM_FERIAS");
                });

            modelBuilder.Entity("Construlink.Models.CrmFeriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("DIA");

                    b.Property<bool?>("Edita")
                        .HasColumnType("bit")
                        .HasColumnName("edita");

                    b.Property<int?>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("MES");

                    b.Property<bool?>("Trabalha")
                        .HasColumnType("bit")
                        .HasColumnName("TRABALHA");

                    b.HasKey("Id");

                    b.ToTable("CRM_FERIADOS");
                });

            modelBuilder.Entity("Construlink.Models.CrmHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("day_of_week");

                    b.Property<bool?>("Domingo")
                        .HasColumnType("bit")
                        .HasColumnName("domingo");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<bool?>("Ispausa")
                        .HasColumnType("bit")
                        .HasColumnName("ispausa");

                    b.Property<bool?>("Sabado")
                        .HasColumnType("bit")
                        .HasColumnName("sabado");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.Property<int?>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("CRM_HORARIO");
                });

            modelBuilder.Entity("Construlink.Models.CrmMotivosisencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigoerp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODIGOERP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Erpid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ERPID");

                    b.HasKey("Id");

                    b.ToTable("CRM_MOTIVOSISENCAO");
                });

            modelBuilder.Entity("Construlink.Models.CrmPaise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Countrid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COUNTRID");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Markettype")
                        .HasColumnType("int")
                        .HasColumnName("MARKETTYPE");

                    b.Property<string>("Saftcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SAFTCODE");

                    b.HasKey("Id");

                    b.ToTable("CRM_PAISES");
                });

            modelBuilder.Entity("Construlink.Models.CrmPicagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("AREA");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA");

                    b.Property<DateTime?>("Entrada")
                        .HasColumnType("datetime")
                        .HasColumnName("ENTRADA");

                    b.Property<DateTime?>("FimAlmoco")
                        .HasColumnType("datetime")
                        .HasColumnName("FIM_ALMOCO");

                    b.Property<double?>("HorasFaltaParcial")
                        .HasColumnType("float");

                    b.Property<DateTime?>("InicioAlmoco")
                        .HasColumnType("datetime")
                        .HasColumnName("INICIO_ALMOCO");

                    b.Property<string>("Ip1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP1");

                    b.Property<string>("Ip2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP2");

                    b.Property<string>("Ip3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP3");

                    b.Property<string>("Ip4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP4");

                    b.Property<bool?>("IsFalta")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFaltaJustificada")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFerias")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFolga")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("LONGITUDE");

                    b.Property<DateTime?>("Saida")
                        .HasColumnType("datetime")
                        .HasColumnName("SAIDA");

                    b.Property<bool?>("SaidaForcada")
                        .HasColumnType("bit")
                        .HasColumnName("SAIDA_FORCADA");

                    b.Property<int?>("Utilizadorid")
                        .HasColumnType("int")
                        .HasColumnName("UTILIZADORID");

                    b.HasKey("Id");

                    b.ToTable("CRM_PICAGEM");
                });

            modelBuilder.Entity("Construlink.Models.CrmPrazoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Erpid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ERPID");

                    b.Property<int?>("Numdias")
                        .HasColumnType("int")
                        .HasColumnName("NUMDIAS");

                    b.HasKey("Id");

                    b.ToTable("CRM_PRAZO_PAGAMENTO");
                });

            modelBuilder.Entity("Construlink.Models.CrmSerieDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Erpid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ERPID");

                    b.Property<bool?>("Isdefault")
                        .HasColumnType("bit")
                        .HasColumnName("ISDEFAULT");

                    b.Property<string>("Layoutid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LAYOUTID");

                    b.Property<int?>("Lojaid")
                        .HasColumnType("int")
                        .HasColumnName("LOJAID");

                    b.Property<string>("Serie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SERIE");

                    b.Property<string>("Setorerp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SETORERP");

                    b.Property<int?>("Tipodocumentoid")
                        .HasColumnType("int")
                        .HasColumnName("TIPODOCUMENTOID");

                    b.Property<int?>("Ultimodocumento")
                        .HasColumnType("int")
                        .HasColumnName("ULTIMODOCUMENTO");

                    b.HasKey("Id");

                    b.ToTable("CRM_SERIE_DOCUMENTO");
                });

            modelBuilder.Entity("Construlink.Models.CrmTipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Class")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CLASS");

                    b.Property<string>("Codigoerp")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CODIGOERP");

                    b.Property<bool?>("Contabilistico")
                        .HasColumnType("bit")
                        .HasColumnName("CONTABILISTICO");

                    b.Property<bool?>("Contacorrente")
                        .HasColumnType("bit")
                        .HasColumnName("CONTACORRENTE");

                    b.Property<bool?>("Custoobra")
                        .HasColumnType("bit")
                        .HasColumnName("CUSTOOBRA");

                    b.Property<string>("Debitocredito")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("DEBITOCREDITO");

                    b.Property<bool?>("Editavel")
                        .HasColumnType("bit")
                        .HasColumnName("EDITAVEL");

                    b.Property<string>("Entradasaida")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ENTRADASAIDA");

                    b.Property<string>("Erpid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ERPID");

                    b.Property<bool?>("IntegraWt")
                        .HasColumnType("bit")
                        .HasColumnName("INTEGRA_WT");

                    b.Property<bool?>("IsAcertoStock")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACERTO_STOCK");

                    b.Property<bool?>("IsDocArmazem")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DOC_ARMAZEM");

                    b.Property<bool?>("IsOrdemFabrico")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ORDEM_FABRICO");

                    b.Property<bool?>("Isdoctransporte")
                        .HasColumnType("bit")
                        .HasColumnName("ISDOCTRANSPORTE");

                    b.Property<bool?>("Isregularizacao")
                        .HasColumnType("bit")
                        .HasColumnName("ISREGULARIZACAO");

                    b.Property<string>("Modulo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("MODULO");

                    b.Property<bool?>("Movstocks")
                        .HasColumnType("bit")
                        .HasColumnName("MOVSTOCKS");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.Property<bool?>("Precoscomiva")
                        .HasColumnType("bit")
                        .HasColumnName("PRECOSCOMIVA");

                    b.Property<string>("Report")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REPORT");

                    b.Property<bool?>("Reservastock")
                        .HasColumnType("bit")
                        .HasColumnName("RESERVASTOCK");

                    b.Property<string>("SelectionFormula")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SELECTION_FORMULA");

                    b.HasKey("Id");

                    b.ToTable("CRM_TIPO_DOCUMENTO");
                });

            modelBuilder.Entity("Construlink.Models.Distrito", b =>
                {
                    b.Property<byte>("CodDistrito")
                        .HasColumnType("tinyint")
                        .HasColumnName("cod_distrito");

                    b.Property<string>("NomeDistrito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_distrito");

                    b.ToTable("distritos");
                });

            modelBuilder.Entity("Construlink.Models.Epis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdEticadata")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Epis");
                });

            modelBuilder.Entity("Construlink.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("AcedeArtigos")
                        .HasColumnType("bit");

                    b.Property<bool?>("AcedeComercial")
                        .HasColumnType("bit");

                    b.Property<bool?>("AcedeContascorrentes")
                        .HasColumnType("bit")
                        .HasColumnName("ACEDE_CONTASCORRENTES");

                    b.Property<bool?>("AcedeDocumentos")
                        .HasColumnType("bit")
                        .HasColumnName("acede_documentos");

                    b.Property<bool?>("AcedeEntidades")
                        .HasColumnType("bit")
                        .HasColumnName("ACEDE_ENTIDADES");

                    b.Property<bool?>("AcedeObras")
                        .HasColumnType("bit")
                        .HasColumnName("ACEDE_OBRAS");

                    b.Property<bool?>("AdjudicaObra")
                        .HasColumnType("bit")
                        .HasColumnName("ADJUDICA_OBRA");

                    b.Property<string>("Agpassword")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AGPASSWORD");

                    b.Property<bool?>("BancoHoras")
                        .HasColumnType("bit")
                        .HasColumnName("BANCO_HORAS");

                    b.Property<DateTime?>("BancoHorasData")
                        .HasColumnType("datetime")
                        .HasColumnName("BANCO_HORAS_DATA");

                    b.Property<decimal?>("BancoHorasStart")
                        .HasColumnType("decimal(10, 1)")
                        .HasColumnName("BANCO_HORAS_START");

                    b.Property<decimal?>("BancoHorasTurno")
                        .HasColumnType("decimal(10, 1)")
                        .HasColumnName("BANCO_HORAS_TURNO");

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CC");

                    b.Property<DateTime?>("Ccvalidade")
                        .HasColumnType("datetime")
                        .HasColumnName("CCValidade");

                    b.Property<bool?>("Changepassword")
                        .HasColumnType("bit")
                        .HasColumnName("CHANGEPASSWORD");

                    b.Property<string>("CodPostal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Comercial")
                        .HasColumnType("bit");

                    b.Property<string>("Concelho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContatoSeguranca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CustoHora")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("CustoHora");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Departamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DEPARTAMENTO");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMPRESA");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("FazPicagens")
                        .HasColumnType("bit")
                        .HasColumnName("FAZ_PICAGENS");

                    b.Property<string>("Funconario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FUNCONARIO");

                    b.Property<bool?>("Geolocation")
                        .HasColumnType("bit")
                        .HasColumnName("GEOLOCATION");

                    b.Property<string>("HabilitacoesLiterarias")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Iban")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IBAN");

                    b.Property<int?>("IdUtilizador")
                        .HasColumnType("int")
                        .HasColumnName("IdCrmUtilizador");

                    b.Property<int?>("IdcomissoesTabela")
                        .HasColumnType("int")
                        .HasColumnName("IDComissoesTabela");

                    b.Property<int?>("Idfuncao")
                        .HasColumnType("int")
                        .HasColumnName("IDFuncao");

                    b.Property<int?>("Inativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InicioTimesheets")
                        .HasColumnType("datetime")
                        .HasColumnName("INICIO_TIMESHEETS");

                    b.Property<bool?>("IsChaoFabrica")
                        .HasColumnType("bit")
                        .HasColumnName("IsChaoFabrica");

                    b.Property<bool?>("IsFuncionario")
                        .HasColumnType("bit");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("ISACTIVE");

                    b.Property<bool?>("Isadmin")
                        .HasColumnType("bit")
                        .HasColumnName("ISADMIN");

                    b.Property<bool?>("Ismanager")
                        .HasColumnType("bit")
                        .HasColumnName("ISMANAGER");

                    b.Property<DateTime?>("Lastlogon")
                        .HasColumnType("datetime")
                        .HasColumnName("LASTLOGON");

                    b.Property<string>("Localidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Macaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MACADDRESS");

                    b.Property<int?>("MontagensFuncionarios")
                        .HasColumnType("int");

                    b.Property<int?>("MontagensResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nib")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NIB");

                    b.Property<string>("Nif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumFilhos")
                        .HasColumnType("int");

                    b.Property<int?>("NumMecanografico")
                        .HasColumnType("int")
                        .HasColumnName("NumMecanografico");

                    b.Property<string>("Obs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observacoes");

                    b.Property<string>("OrdemMapas")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Pin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PIN");

                    b.Property<bool?>("PreencheTs")
                        .HasColumnType("bit")
                        .HasColumnName("PREENCHE_TS");

                    b.Property<int?>("Reportto")
                        .HasColumnType("int")
                        .HasColumnName("REPORTTO");

                    b.Property<string>("SegSocial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Seguro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SenhaProvisoria")
                        .HasColumnType("int");

                    b.Property<bool?>("SoObras")
                        .HasColumnType("bit")
                        .HasColumnName("so_obras");

                    b.Property<string>("Swift")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserCf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_CF");

                    b.Property<string>("Username")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USERNAME");

                    b.Property<bool?>("ValidaPicagens")
                        .HasColumnType("bit")
                        .HasColumnName("VALIDA_PICAGENS");

                    b.Property<bool?>("VeValore")
                        .HasColumnType("bit")
                        .HasColumnName("veValore");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Construlink.Models.FuncionarioFerias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FuncionarioFerias");
                });

            modelBuilder.Entity("Construlink.Models.FuncionarioObraAgendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FaltouParcialmente")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraPausa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraRetorno")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraSaida")
                        .HasColumnType("time");

                    b.Property<double?>("HorasExtras")
                        .HasColumnType("float");

                    b.Property<double?>("HorasNormais")
                        .HasColumnType("float");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Trabalhou")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FuncionarioObraAgendamento");
                });

            modelBuilder.Entity("Construlink.Models.NiveisPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Adicional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NiveisPreco");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pCondpagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condpag")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CONDPAG");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Dias")
                        .HasColumnType("int")
                        .HasColumnName("DIAS");

                    b.Property<int?>("Empresaid")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESAID");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_CONDPAGAMENTO");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pEntidadesErp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CP");

                    b.Property<string>("CpLoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CP_LOC");

                    b.Property<int?>("Empresaid")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESAID");

                    b.Property<string>("Entidade")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ENTIDADE");

                    b.Property<string>("Localidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Moeda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MOEDA");

                    b.Property<string>("Morada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MORADA");

                    b.Property<string>("Morada2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MORADA2");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Nomefiscal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOMEFISCAL");

                    b.Property<string>("Numcontrib")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NUMCONTRIB");

                    b.Property<string>("Pais")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("PAIS");

                    b.Property<string>("Tel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEL");

                    b.Property<string>("Tipoentidade")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("TIPOENTIDADE");

                    b.Property<string>("Tipomercado")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("TIPOMERCADO");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_ENTIDADES_ERP");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Empresaid")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESAID");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ORDEM");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_ESTADOS");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pFraco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Andar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ANDAR");

                    b.Property<string>("Areabruta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AREABRUTA");

                    b.Property<string>("Areautil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AREAUTIL");

                    b.Property<string>("Bloco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BLOCO");

                    b.Property<string>("Cliente")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CLIENTE");

                    b.Property<string>("CodigoObraPai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoObraPai");

                    b.Property<DateTime?>("DataCpcv")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_CPCV");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ENTREGA");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Garagem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GARAGEM");

                    b.Property<string>("Imagem")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("IMAGEM");

                    b.Property<string>("Imobiliaria")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("IMOBILIARIA");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Notas")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("NOTAS");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TIPOLOGIA");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_FRACOES");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pImobiliariasObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Entidade")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("ENTIDADE");

                    b.Property<int?>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("OBRA_ID");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_IMOBILIARIAS_OBRA");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pModospagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Empresaid")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESAID");

                    b.Property<string>("Movim")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MOVIM");

                    b.Property<string>("Tipomv")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("TIPOMV");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_MODOSPAGAMENTO");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alvara")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ALVARA");

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("AREA");

                    b.Property<string>("Cliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLIENTE");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CODIGO_POSTAL");

                    b.Property<string>("CondPag")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("COND_PAG");

                    b.Property<string>("Construtor")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CONSTRUTOR");

                    b.Property<int?>("CriadaPor")
                        .HasColumnType("int")
                        .HasColumnName("CRIADA_POR");

                    b.Property<DateTime?>("DataAdjudicacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ADJUDICACAO");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("DELETED");

                    b.Property<bool?>("DesbloquearSubempreitadas")
                        .HasColumnType("bit")
                        .HasColumnName("DESBLOQUEAR_SUBEMPREITADAS");

                    b.Property<int?>("Empresaid")
                        .HasColumnType("int")
                        .HasColumnName("EMPRESAID");

                    b.Property<string>("ErpId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ERP_ID");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime?>("FimPrevisto")
                        .HasColumnType("datetime")
                        .HasColumnName("FIM_PREVISTO");

                    b.Property<DateTime?>("FimReal")
                        .HasColumnType("datetime")
                        .HasColumnName("FIM_REAL");

                    b.Property<int?>("Gestor")
                        .HasColumnType("int")
                        .HasColumnName("GESTOR");

                    b.Property<DateTime?>("InicioPrevisto")
                        .HasColumnType("datetime")
                        .HasColumnName("INICIO_PREVISTO");

                    b.Property<bool?>("Isempreendimento")
                        .HasColumnType("bit")
                        .HasColumnName("ISEMPREENDIMENTO");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("LocalPostal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOCAL_POSTAL");

                    b.Property<string>("Localidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("ModoPag")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MODO_PAG");

                    b.Property<string>("Morada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MORADA");

                    b.Property<string>("Nome")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NOME");

                    b.Property<string>("Obs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OBS");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_ID");

                    b.Property<int?>("Processoid")
                        .HasColumnType("int")
                        .HasColumnName("PROCESSOID");

                    b.Property<string>("Promotor")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("PROMOTOR");

                    b.Property<decimal?>("TotalEoAprovados")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("TOTAL_EO_APROVADOS");

                    b.Property<decimal?>("TotalRevisaoPrecosAprovados")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("TOTAL_REVISAO_PRECOS_APROVADOS");

                    b.Property<decimal?>("TotalTmaisAprovados")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("TOTAL_TMAIS_APROVADOS");

                    b.Property<DateTime?>("ValidadeAlvara")
                        .HasColumnType("datetime")
                        .HasColumnName("VALIDADE_ALVARA");

                    b.Property<decimal?>("ValorAdjudicacao")
                        .HasColumnType("money")
                        .HasColumnName("VALOR_ADJUDICACAO");

                    b.Property<decimal?>("ValorReorcamento")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("VALOR_REORCAMENTO");

                    b.Property<decimal?>("ValorSeco")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("VALOR_SECO");

                    b.Property<decimal?>("ValorTotalEstMat")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("VALOR_TOTAL_EST_MAT");

                    b.Property<decimal?>("ValorTotalEstSubempreitada")
                        .HasColumnType("decimal(37, 2)")
                        .HasColumnName("VALOR_TOTAL_EST_SUBEMPREITADA");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_OBRA");
                });

            modelBuilder.Entity("Construlink.Models.OsusrN2pProcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Parentid")
                        .HasColumnType("int")
                        .HasColumnName("PARENTID");

                    b.Property<int?>("Responsavel")
                        .HasColumnType("int")
                        .HasColumnName("RESPONSAVEL");

                    b.HasKey("Id");

                    b.ToTable("OSUSR_N2P_PROCESSO");
                });

            modelBuilder.Entity("Construlink.Models.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("TipoTurno");
                });

            modelBuilder.Entity("Construlink.Models.Turnos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("Entrada")
                        .HasColumnType("time");

                    b.Property<string>("NomeTipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomeTipo");

                    b.Property<TimeSpan?>("Pausa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Retorno")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("Saida")
                        .HasColumnType("time");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Construlink.Models.CrmAusencia", b =>
                {
                    b.HasOne("Construlink.Models.Funcionario", "Colaborador")
                        .WithMany()
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });
#pragma warning restore 612, 618
        }
    }
}
